<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="demoWSService" targetNamespace="http://tcss559.net/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://tcss559.net/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://tcss559.net/" schemaLocation="demows_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="addResponse">
    <wsdl:part name="parameters" element="tns:addResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="add">
    <wsdl:part name="parameters" element="tns:add">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="demoWS">
    <wsdl:operation name="add">
      <wsdl:input name="add" message="tns:add">
    </wsdl:input>
      <wsdl:output name="addResponse" message="tns:addResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="demoWSServiceSoapBinding" type="tns:demoWS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="add">
      <soap:operation soapAction="urn:add" style="document"/>
      <wsdl:input name="add">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="addResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="demoWSService">
    <wsdl:port name="demoWSPort" binding="tns:demoWSServiceSoapBinding">
      <soap:address location="http://localhost:8080/demoWS/services"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
