
package net.tcss559.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.4
 * Thu Oct 27 14:52:30 PDT 2022
 * Generated source version: 3.5.4
 */

@XmlRootElement(name = "enrollStudent", namespace = "http://tcss559.net/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "enrollStudent", namespace = "http://tcss559.net/", propOrder = {"name", "studentID"})

public class EnrollStudent {

    @XmlElement(name = "name")
    private java.lang.String name;
    @XmlElement(name = "studentID")
    private int studentID;

    public java.lang.String getName() {
        return this.name;
    }

    public void setName(java.lang.String newName)  {
        this.name = newName;
    }

    public int getStudentID() {
        return this.studentID;
    }

    public void setStudentID(int newStudentID)  {
        this.studentID = newStudentID;
    }

}

