
package net.tcss559.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.4
 * Thu Oct 27 14:52:30 PDT 2022
 * Generated source version: 3.5.4
 */

@XmlRootElement(name = "helperUpdate", namespace = "http://tcss559.net/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "helperUpdate", namespace = "http://tcss559.net/", propOrder = {"arg0", "arg1", "arg2"})

public class HelperUpdate {

    @XmlElement(name = "arg0")
    private int arg0;
    @XmlElement(name = "arg1")
    private int arg1;
    @XmlElement(name = "arg2")
    private double arg2;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

    public int getArg1() {
        return this.arg1;
    }

    public void setArg1(int newArg1)  {
        this.arg1 = newArg1;
    }

    public double getArg2() {
        return this.arg2;
    }

    public void setArg2(double newArg2)  {
        this.arg2 = newArg2;
    }

}

