
package net.tcss559.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.4
 * Thu Oct 27 16:26:29 PDT 2022
 * Generated source version: 3.5.4
 */

@XmlRootElement(name = "ParserConfigurationException", namespace = "http://parsers.xml.javax/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParserConfigurationException", namespace = "http://parsers.xml.javax/")

public class ParserConfigurationExceptionBean {

    private java.lang.String message;

    public java.lang.String getMessage() {
        return this.message;
    }

    public void setMessage(java.lang.String newMessage)  {
        this.message = newMessage;
    }

}

